//
//  HLanguage.cpp
//  card
//
//  Created by bo wei on 13-7-11.
//
//

#include "HLanguage.h"


HSINGLETON_OBJECT_IMP(HLanguage);

HLanguage::HLanguage(){
    init();
}
HLanguage::~HLanguage(){}

void HLanguage::init()
{
    static int initialized = false;
    static const char *languageData[] = {
        "MSG_CODE_100" ,    ccLocalizedString("HSYS_MSG_TIMEOUT"),
        "MSG_CODE_1000",    ccLocalizedString("HSYS_ACC_REG_ILLEGAL"),
        "MSG_CODE_1001",    ccLocalizedString("HSYS_DEVICE_REG_FORBID"),
        "MSG_CODE_1002",    ccLocalizedString("HSYS_DEVICE_REG_MAX"),
        "MSG_CODE_1003",    ccLocalizedString("HSYS_ACC_ERROR"),
        "MSG_CODE_1004",    ccLocalizedString("HSYS_PWD_ACC_ERROR"),
        "MSG_CODE_1005",    ccLocalizedString("HSYS_NO_SERVER"),
        "MSG_CODE_1010",    ccLocalizedString("HSYS_NO_ACCOUNT"),
        "MSG_CODE_1011",    ccLocalizedString("HSYS_NO_ACCOUNT"),
        "MSG_CODE_1012",    ccLocalizedString("HSYS_ACC_PWD_ERROR"),
        "MSG_CODE_1013",    ccLocalizedString("HSYS_ACC_HAS_REG"),
        "MSG_CODE_1014",    ccLocalizedString("HSYS_MAIL_ERROR"),
        "MSG_CODE_1017",    ccLocalizedString("HSYS_NFIND_ACC"),
        "MSG_CODE_1024",    ccLocalizedString("HSYS_GCID_ERROR"),
        "MSG_CODE_-10000",  ccLocalizedString("HSYS_NCON_SERVER_2"),
        "MSG_CODE_2000",    ccLocalizedString("HSYS_NCON_SERVER_2"),
        "MSG_CODE_2012",    ccLocalizedString("HSYS_INVATE_ERROR"),
        "MSG_CODE_10001",	ccLocalizedString("HSYS_ACC_NEXIST"),
        "MSG_CODE_10002",	ccLocalizedString("HSYS_ACC_EXIST"),
        "MSG_CODE_10003",	ccLocalizedString("HSYS_PWD_ERROR"),
        "MSG_CODE_10004",	ccLocalizedString("HSYS_ACC_ERROR"),
        "MSG_CODE_10005",	ccLocalizedString("HSYS_ACCN_EXIST"),
        "MSG_CODE_10006",	ccLocalizedString("HSYS_LENGTH_ERROR"),
        "MSG_CODE_10007",	ccLocalizedString("HSYS_UPDATE_CONFIG"),
        "MSG_CODE_10008",	ccLocalizedString("HSYS_UPDATE_CLIENT"),
        "MSG_CODE_10009",	ccLocalizedString("HSYS_ACCN_CHANGED"),
        "MSG_CODE_10010",	ccLocalizedString("HSYS_AUTHORITY_LIMIT"),
        "MSG_CODE_10011",	ccLocalizedString("HSYS_NEED_RELOGIN"),
        "MSG_CODE_10011",	ccLocalizedString("HSYS_SERVER_ERROR_RETRY"),
        "MSG_CODE_10013",	ccLocalizedString("HSYS_CLIENT_VER_ERROR"),
        "MSG_CODE_10014",	ccLocalizedString("HSYS_ACC_CLOSED"),
        "MSG_CODE_20001",	ccLocalizedString("HSYS_CONFIG_NEXIST"),
        "MSG_CODE_30001",	ccLocalizedString("HSYS_CARDG_NEXIST"),
        "MSG_CODE_30002",	ccLocalizedString("HSYS_CARD_NEXIST"),
        "MSG_CODE_30003",	ccLocalizedString("HSYS_MAGIC_NEXIST"),
        "MSG_CODE_30004",	ccLocalizedString("HSYS_HERO_NEXIST"),
        "MSG_CODE_30005",	ccLocalizedString("HSYS_CARDG_NEMPTY"),
        "MSG_CODE_30006",	ccLocalizedString("HSYS_MAGICG_NEMPTY"),
        "MSG_CODE_30007",	ccLocalizedString("HSYS_HERO_MD_NEXIST"),
        "MSG_CODE_30008",	ccLocalizedString("HSYS_STRONG_CARD_MD_NEXIST"),
        "MSG_CODE_30009",	ccLocalizedString("HSYS_CARD_MD_NEXIST"),
        "MSG_CODE_30010",	ccLocalizedString("HSYS_COIN_LESS"),
        "MSG_CODE_30011",	ccLocalizedString("HSYS_CARD_LV_MAX"),
        "MSG_CODE_30012",	ccLocalizedString("HSYS_STRONG_CARD_NEED_MATERIAL"),
        "MSG_CODE_30013",	ccLocalizedString("HSYS_STRONG_NSAME"),
        "MSG_CODE_30014",	ccLocalizedString("HSYS_STRONG_MAGIC_MD_NEXIST"),
        "MSG_CODE_30015",	ccLocalizedString("HSYS_MAGIC_MD_NEXIST"),
        "MSG_CODE_30016",	ccLocalizedString("HSYS_MAGIC_LV_MAX"),
        "MSG_CODE_30017",	ccLocalizedString("HSYS_STRONG_MAGIC_NEED_MATERIAL"),
        "MSG_CODE_30018",	ccLocalizedString("HSYS_USERINFO_NEXIST"),
        "MSG_CODE_30019",	ccLocalizedString("HSYS_CARD_NUM_MAX"),
        "MSG_CODE_30020",	ccLocalizedString("HSYS_MAGIC_NUM_MAX"),
        "MSG_CODE_30021",	ccLocalizedString("HSYS_GOLD_LESS"),
        "MSG_CODE_30022",	ccLocalizedString("HSYS_LEADER_LESS"),
        "MSG_CODE_30023",	ccLocalizedString("HSYS_HAS_IN_CARDG"),
        "MSG_CODE_30024",	ccLocalizedString("HSYS_NCARD_IN_CARDG"),
        "MSG_CODE_30025",	ccLocalizedString("HSYS_CARD_FULL_TOSELL"),
        "MSG_CODE_30026",	ccLocalizedString("HSYS_MAGIC_FULL_TOSELL"),
        "MSG_CODE_30027",	ccLocalizedString("HSYS_CARD_MAX_ERR"),
        "MSG_CODE_30028",	ccLocalizedString("HSYS_MAGIC_MAX_ERR"),
        "MSG_CODE_30029",	ccLocalizedString("HSYS_HERO_LV_LESS"),
        "MSG_CODE_30030",	ccLocalizedString("HSYS_NSAME_MAGIC"),
        "MSG_CODE_30031",	ccLocalizedString("HSYS_STONE_LESS"),
        "MSG_CODE_30032",   ccLocalizedString("HSYS_MONSTER_MD_NEXIST"),
        "MSG_CODE_40001",	ccLocalizedString("HSYS_IN_BATTLING"),
        "MSG_CODE_40002",	ccLocalizedString("HSYS_BATTLE_NEXIST"),
        "MSG_CODE_40003",	ccLocalizedString("HSYS_NMOVE_W2B"),
        "MSG_CODE_40004",	ccLocalizedString("HSYS_NTURN_YOU"),
        "MSG_CODE_40005",	ccLocalizedString("HSYS_BATTLE_TYPE_NEXIST"),
        "MSG_CODE_40006",	ccLocalizedString("HSYS_POWER_LESS"),
        "MSG_CODE_40007",	ccLocalizedString("HSYS_BAT_P1_NEXIST"),
        "MSG_CODE_40008",	ccLocalizedString("HSYS_BAT_P2_NEXIST"),
        "MSG_CODE_50001",	ccLocalizedString("HSYS_MAP_NEXIST"),
        "MSG_CODE_50002",	ccLocalizedString("HSYS_MAP_NOPEN"),
        "MSG_CODE_50003",	ccLocalizedString("HSYS_MAP_MD_NEXIST"),
        "MSG_CODE_50004",	ccLocalizedString("HSYS_INCOME_GOT"),
        "MSG_CODE_60001",	ccLocalizedString("HSYS_TS_OUT_MAX"),
        "MSG_CODE_60002",	ccLocalizedString("HSYS_TS_ILLEGAL"),
        "MSG_CODE_60003",	ccLocalizedString("HSYS_TS_MD_NEXIST"),
        "MSG_CODE_60004",	ccLocalizedString("HSYS_TS_NUM_MAX"),
        "MSG_CODE_60005",	ccLocalizedString("HSYS_BEAD_NEXIST"),
        "MSG_CODE_60006",	ccLocalizedString("HSYS_BEAD_LESS"),
        "MSG_CODE_60007",	ccLocalizedString("HSYS_HAS_HERE"),
        "MSG_CODE_70001",	ccLocalizedString("HSYS_MALL_NEXIST"),
        "MSG_CODE_70002",	ccLocalizedString("HSYS_BUY_OBJ_NEXIST"),
        "MSG_CODE_70003",	ccLocalizedString("HSYS_BUY_OBJ_NEXIST"),
        "MSG_CODE_70004",	ccLocalizedString("HSYS_BUY_OBJ_PASS"),
        "MSG_CODE_70005",	ccLocalizedString("HSYS_BUY_ONLY_ONCE"),
        "MSG_CODE_80001",	ccLocalizedString("HSYS_STORE_INFO_NEXIST"),
        "MSG_CODE_80002",	ccLocalizedString("HSYS_POWER_R_MAX"),
        "MSG_CODE_80003",	ccLocalizedString("HSYS_POWER_BUY_R_MAX"),
        "MSG_CODE_90001",	ccLocalizedString("HSYS_HEAVEN_NEXIST"),
        "MSG_CODE_90002",	ccLocalizedString("HSYS_HEAVEN_MD_NEXIST"),
        "MSG_CODE_90003",	ccLocalizedString("HSYS_HEAVEN_ID_ILLEGAL"),
        "MSG_CODE_90004",	ccLocalizedString("HSYS_HEAVEN_EVENT_NEXIST"),
        "MSG_CODE_90005",	ccLocalizedString("HSYS_HEAVEN_HAS_PASS"),
        "MSG_CODE_90006",	ccLocalizedString("HSYS_HEAVEN_RESET_MAX"),
        "MSG_CODE_90007",	ccLocalizedString("HSYS_HEAVEN_BUY_MAX"),
        "MSG_CODE_100001",	ccLocalizedString("HSYS_FRIEND_NEXIST"),
        "MSG_CODE_100002",	ccLocalizedString("HSYS_NIN_APPLY_LIST"),
        "MSG_CODE_100003",	ccLocalizedString("HSYS_NIN_FRIEND_LIST"),
        "MSG_CODE_100004",	ccLocalizedString("HSYS_IN_FRIEND_LIST"),
        "MSG_CODE_100005",	ccLocalizedString("HSYS_NCAN_SELF"),
        "MSG_CODE_100006",	ccLocalizedString("HSYS_FRIEND_OUT_LIMIT"),
        "MSG_CODE_100007",	ccLocalizedString("HSYS_PAGE_ERROR"),
        "MSG_CODE_100008",	ccLocalizedString("HSYS_NGIVE_POWER"),
        "MSG_CODE_100009",	ccLocalizedString("HSYS_NGET_POWER"),
        "MSG_CODE_100010",	ccLocalizedString("HSYS_INVATE_MD_NEXIST"),
        "MSG_CODE_100011",	ccLocalizedString("HSYS_TARGET_FRIEND_OUT_LIMIT"),
        "MSG_CODE_110001" , ccLocalizedString("HSYS_THIEF_NEXIST"),
        "MSG_CODE_110002" , ccLocalizedString("HSYS_THIEF_NAPPEAR"),
        "MSG_CODE_110003" , ccLocalizedString("HSYS_THIEF_KILLED"),
        "MSG_CODE_110004" , ccLocalizedString("HSYS_THIEF_RUN"),
        "MSG_CODE_110005" , ccLocalizedString("HSYS_THIEF_NCD"),
        "MSG_CODE_110006" , ccLocalizedString("HSYS_THIEF_KILL_FAILD"),
        "MSG_CODE_110007" , ccLocalizedString("HSYS_THIEF_CREATE_FAILD"),
        "MSG_CODE_110008" , ccLocalizedString("HSYS_THIEF_NACTIVATE"),
        "MSG_CODE_110009" , ccLocalizedString("HSYS_THIEF_LV_LESS"),
        "MSG_CODE_110010" , ccLocalizedString("HSYS_THIEF_PLAYER_NEXIST"),
        "MSG_CODE_110011" , ccLocalizedString("HSYS_THIEF_TASK_MAX"),
        "MSG_CODE_110012" , ccLocalizedString("HSYS_THIEF_RESET_NCD"),
        "MSG_CODE_110013" , ccLocalizedString("HSYS_THIEF_TASK_NFULFIL"),
        "MSG_CODE_110014" , ccLocalizedString("HSYS_THIEF_TASK_NEXIST"),
        "MSG_CODE_110015" , ccLocalizedString("HSYS_THIEF_TASK_MD_NEXIST"),
        "MSG_CODE_120001",	ccLocalizedString("HSYS_CFRAG_NEXIST"),
        "MSG_CODE_120002",	ccLocalizedString("HSYS_CFRAG_LESS"),
        "MSG_CODE_120003",	ccLocalizedString("HSYS_CFRAG_MD_NEXIST"),
        "MSG_CODE_130001",	ccLocalizedString("HSYS_REPLAY_NEXIST"),
        "MSG_CODE_130002",	ccLocalizedString("HSYS_REPLAY_ID_NEXIST"),
        "MSG_CODE_130003",	ccLocalizedString("HSYS_REPLAY_VER_ERR"),
        "MSG_CODE_130004",	ccLocalizedString("HSYS_REPLAY_BAT_NEXIST"),
        "MSG_CODE_140001",	ccLocalizedString("HSYS_AWAKE_ACTIVATED"),
        "MSG_CODE_140002",	ccLocalizedString("HSYS_AWAKE_NEXIST"),
        "MSG_CODE_140003",	ccLocalizedString("HSYS_AWAKE_ILLEGAL"),
        "MSG_CODE_140004",	ccLocalizedString("HSYS_AWAKE_NACTIVATE"),
        "MSG_CODE_140005",	ccLocalizedString("HSYS_AFRAG_LESS"),
        "MSG_CODE_140006",	ccLocalizedString("HSYS_PROP_ERROR"),
        "MSG_CODE_140007",	ccLocalizedString("HSYS_PROP_NEXIST"),
        "MSG_CODE_140008",	ccLocalizedString("HSYS_PROP_LV_LESS"),
        "MSG_CODE_140009",	ccLocalizedString("HSYS_AFRAG_NEXIST"),
        "MSG_CODE_140010",	ccLocalizedString("HSYS_ACARD_NSAME"),
        "MSG_CODE_150001",	ccLocalizedString("HSYS_FS_NEXIST"),
        "MSG_CODE_150002",	ccLocalizedString("HSYS_FS_LVUP_NEED_MAT"),
        "MSG_CODE_150003",	ccLocalizedString("HSYS_FS_LV_MAX"),
        "MSG_CODE_150004",	ccLocalizedString("HSYS_FS_MD_NEXIST"),
        "MSG_CODE_160001",	ccLocalizedString("HSYS_PVP_NEXIST"),
        "MSG_CODE_160002",	ccLocalizedString("HSYS_PVP_NUM_MAX"),
        "MSG_CODE_160003",	ccLocalizedString("HSYS_PVP_BUY_MAX"),
        "MSG_CODE_160004",	ccLocalizedString("HSYS_PVP_BUY_MAX"),
        "MSG_CODE_160005",	ccLocalizedString("HSYS_PVP_P2_NEXIST"),
        "MSG_CODE_160006",	ccLocalizedString("HSYS_PVP_RANK_NEXIST"),
        "MSG_CODE_160007",	ccLocalizedString("HSYS_PVP_NBAT_LOWER"),
        "MSG_CODE_160008",	ccLocalizedString("HSYS_PVPG_NEXIST"),
        "MSG_CODE_160009",	ccLocalizedString("HSYS_PVP_USER_NEXIST"),
        "MSG_CODE_160010",	ccLocalizedString("HSYS_PVPG_NSAME"),
        "MSG_CODE_160011",	ccLocalizedString("HSYS_PVP_POINT_LESS"),
        "MSG_CODE_160012",	ccLocalizedString("HSYS_PVP_REFRESH_WAIT"),
        "MSG_CODE_160013",	ccLocalizedString("HSYS_PVP_LAYER_MAX"),
        "MSG_CODE_160014",	ccLocalizedString("HSYS_PVP_TPOINT_LESS"),
        "MSG_CODE_160015",	ccLocalizedString("HSYS_PVP_RANK_LESS"),
        "MSG_CODE_160016",	ccLocalizedString("HSYS_PVP_REWARD_NEXIST"),
        "MSG_CODE_160017",	ccLocalizedString("HSYS_PVP_NCD"),
        "MSG_CODE_160018",	ccLocalizedString("HSYS_PVP_UG_NCD"),
        "MSG_CODE_160019",	ccLocalizedString("HSYS_PVP_UG_REWARD_NEXIST"),
        "MSG_CODE_160020",	ccLocalizedString("HSYS_PVP_UG_REWARD_GOT"),
        "MSG_CODE_160021",	ccLocalizedString("HSYS_PVP_UG_REWARD_ILLEGAL"),
        "MSG_CODE_160022",	ccLocalizedString("HSYS_PVP_UG_NPC_NEXIST"),
        "MSG_CODE_160023",	ccLocalizedString("HSYS_PVP_NPC_MD_NEXIST"),
        "MSG_CODE_160024",	ccLocalizedString("HSYS_PVP_LAYER_LESS"),
        
        "MSG_CODE_170001",	ccLocalizedString("HSYS_COL_NEXIST"),
        "MSG_CODE_170002",	ccLocalizedString("HSYS_COL_USER_NEXIST"),
        "MSG_CODE_170003",	ccLocalizedString("HSYS_OVER_STEP"),
        "MSG_CODE_170004",	ccLocalizedString("HSYS_SIGNUP_PASS"),
        "MSG_CODE_170005",	ccLocalizedString("HSYS_HAS_SIGNUP"),
        "MSG_CODE_170006",	ccLocalizedString("HSYS_NSIGNUP"),
        "MSG_CODE_170007",	ccLocalizedString("HSYS_DRAW_NUM_MAX"),
        "MSG_CODE_170008",	ccLocalizedString("HSYS_COL_MD_NEXIST"),
        "MSG_CODE_170009",	ccLocalizedString("HSYS_COL_CARD_NEXIST"),
        "MSG_CODE_170010",	ccLocalizedString("HSYS_COL_RCARD_NEXIST"),
        "MSG_CODE_170011",	ccLocalizedString("HSYS_COL_RCARD_NIN_BAT"),
        "MSG_CODE_170012",	ccLocalizedString("HSYS_COL_CARD_NUM_ERR"),
        "MSG_CODE_170013",	ccLocalizedString("HSYS_COL_LEADED_LESS"),
        "MSG_CODE_170014",	ccLocalizedString("HSYS_COL_HX_NEND"),
        "MSG_CODE_170015",	ccLocalizedString("HSYS_COL_JS_NEND"),
        "MSG_CODE_170016",	ccLocalizedString("HSYS_COL_JS_POS_ERR"),
        
        "MSG_CODE_180001",	ccLocalizedString("HSYS_MAIL_NEXIST"),
        "MSG_CODE_180002",	ccLocalizedString("HSYS_MAIL_ID_NEXIST"),
        
        "MSG_CODE_190001",	ccLocalizedString("HSYS_REWARD_NEXIST"),
        "MSG_CODE_190002",	ccLocalizedString("HSYS_REWARD_NEMPTY"),
        
        "MSG_CODE_200001",	ccLocalizedString("HSYS_HANDBOOK_NEXIST"),
        
        "MSG_CODE_210001",	ccLocalizedString("HSYS_ACTIVE_NEXIST"),
        "MSG_CODE_210002",	ccLocalizedString("HSYS_ACTIVE_NSTART"),
        "MSG_CODE_210003",	ccLocalizedString("HSYS_ACTIVE_ENDED"),
        "MSG_CODE_210004",	ccLocalizedString("HSYS_ACTIVE_NIN_TIME"),
        "MSG_CODE_210005",	ccLocalizedString("HSYS_HAS_GOT"),
        "MSG_CODE_210006",	ccLocalizedString("HSYS_TREE_LV_MAX"),
        "MSG_CODE_210007",	ccLocalizedString("HSYS_ACTIVE_INVALID"),
        "MSG_CODE_210008",	ccLocalizedString("HSYS_CHECKIN_ONLY_ONCE"),
        "MSG_CODE_210009",	ccLocalizedString("HSYS_CHECKIN_MD_NEXIST"),
        "MSG_CODE_210010",	ccLocalizedString("HSYS_ACTIVE_NACTIVATE"),
        "MSG_CODE_210011", ccLocalizedString("HSYS_BOX_MD_NEXIST"),
        "MSG_CODE_210012", ccLocalizedString("HSYS_BOX_ID_INVALID"),
        "MSG_CODE_210013" , ccLocalizedString("HSYS_TURN_TASK_NEXIST"),
        "MSG_CODE_210014" , ccLocalizedString("HSYS_TURN_TASK_MD_NEXIST"),
        "MSG_CODE_210015" , ccLocalizedString("HSYS_TURN_LUCK_LESS"),
        "MSG_CODE_210016" , ccLocalizedString("HSYS_BAGUA_MD_NEXIST"),
        "MSG_CODE_210017" , ccLocalizedString("HSYS_BAGUA_NUM_LESS"),
        "MSG_CODE_210018" , ccLocalizedString("HSYS_EXC_MD_NEXIST"),
        "MSG_CODE_210019" , ccLocalizedString("HSYS_EXC_NFULFIL"),
        "MSG_CODE_210020" , ccLocalizedString("HSYS_EXC_POS_MD_NEXIST"),
        "MSG_CODE_210021" , ccLocalizedString("HSYS_CHARGE_TIME_INVALID"),
        "MSG_CODE_210022" , ccLocalizedString("HSYS_CHARGE_USER_NEXIST"),
        "MSG_CODE_210023" , ccLocalizedString("HSYS_CHARGE_REWARD_WAIT"),
        "MSG_CODE_210024" , ccLocalizedString("HSYS_CHARGE_TIME_NUPDATE"),
        "MSG_CODE_210025" , ccLocalizedString("HSYS_CHARGE_REWARD_SENDED"),
        "MSG_CODE_210026" , ccLocalizedString("HSYS_CONSUME_TIME_INVALID"),
        "MSG_CODE_210027" , ccLocalizedString("HSYS_CONSUME_USER_NEXIST"),
        "MSG_CODE_210028" , ccLocalizedString("HSYS_CONSUME_REWARD_WAIT"),
        "MSG_CODE_210029" , ccLocalizedString("HSYS_CONSUME_TIME_NUPDATE"),
        "MSG_CODE_210030" , ccLocalizedString("HSYS_CONSUME_REWARD_SENDED"),
        
        "MSG_CODE_220001",	ccLocalizedString("HSYS_ACHIEVE_NEXIST"),
        
        "MSG_CODE_230001",	ccLocalizedString("HSYS_VIP_NEXIST"),
        "MSG_CODE_230002",	ccLocalizedString("HSYS_VIP_REWARD_GOT"),
        "MSG_CODE_230003",	ccLocalizedString("HSYS_VIP_MD_NEXIST"),
        "MSG_CODE_230004",	ccLocalizedString("HSYS_VIP_NEEDED"),
        "MSG_CODE_230005",	ccLocalizedString("HSYS_VIP_LV_LESS"),
        
        "MSG_CODE_240001",	ccLocalizedString("HSYS_AVATAR_INVALID"),
        "MSG_CODE_240002" , ccLocalizedString("HSYS_LIMIT_CHARGE_NEXIST"),
        
        "MSG_CODE_250001",	ccLocalizedString("HSYS_NEWBIE_MD_NEXIST"),
        
        "MSG_CODE_260001",	ccLocalizedString("HSYS_IAP_GOLD_HAS_ADDED"),
        "MSG_CODE_260002",	ccLocalizedString("HSYS_NEXTRA_INFO"),
        "MSG_CODE_260003",	ccLocalizedString("HSYS_NEXTRA_INFO"),
        "MSG_CODE_260004",	ccLocalizedString("HSYS_BUY_INFO_NEXIST"),
        "MSG_CODE_260005",	ccLocalizedString("HSYS_BUY_ONLY_ONCE"),
        
        "MSG_CODE_270001",	ccLocalizedString("HSYS_BRIEF_NEXIST"),
        
        "MSG_CODE_280001",	ccLocalizedString("HSYS_DUNGON_NEXIST"),
        "MSG_CODE_280002",	ccLocalizedString("HSYS_DUNGON_MD_NEXIST"),
        "MSG_CODE_280003",	ccLocalizedString("HSYS_NCHALLENGE_UNKONOW_ERR"),
        "MSG_CODE_280004",	ccLocalizedString("HSYS_DUNGON_NUM_MAX"),
        "MSG_CODE_280005",	ccLocalizedString("HSYS_DUNGON_RESET_MAX"),
        
        "MSG_CODE_290001",	ccLocalizedString("HSYS_HELL_NEXIST"),
        "MSG_CODE_290002",	ccLocalizedString("HSYS_HELL_NREFRESH"),
        "MSG_CODE_290003",	ccLocalizedString("HSYS_HELL_HISINFO_NEXIST"),
        "MSG_CODE_290004",	ccLocalizedString("HSYS_HELL_USERINFO_NEXIST"),
        "MSG_CODE_290005",	ccLocalizedString("HSYS_HELL_MD_NEXIST"),
        "MSG_CODE_290006",	ccLocalizedString("HSYS_HELL_BAT_MAX"),
        "MSG_CODE_290007",	ccLocalizedString("HSYS_HELL_UPDATE_WAIT"),
        "MSG_CODE_290008" , ccLocalizedString("HSYS_HELL_HAS_DIRECT"),
        "MSG_CODE_290009" , ccLocalizedString("HSYS_HELL_NO_DIRECT"),
        
        "MSG_CODE_300001" , ccLocalizedString("HSYS_BOSS_NREFRESH"),
        "MSG_CODE_300002" , ccLocalizedString("HSYS_BOSS_MD_NEXIST"),
        "MSG_CODE_300003" , ccLocalizedString("HSYS_BOSS_PLAYER_NEXIST"),
        "MSG_CODE_300004" , ccLocalizedString("HSYS_BOSS_CUR_PLAYER_NEXIST"),
        "MSG_CODE_300005" , ccLocalizedString("HSYS_BOSS_NEXIST"),
        "MSG_CODE_300006" , ccLocalizedString("HSYS_BOSS_KILLED"),
        "MSG_CODE_300007" , ccLocalizedString("HSYS_BOSS_RUN"),
        "MSG_CODE_300008" , ccLocalizedString("HSYS_BOSS_NCD"),
        "MSG_CODE_300009" , ccLocalizedString("HSYS_BOSS_UPDATE_WAIT"),
        
        "MSG_CODE_240001", "用户头像无效",
        "MSG_CODE_240002", "限时充值不存在",
        "MSG_CODE_240003", "限时消费不存在",
        "MSG_CODE_280001", "副本不存在",
        "MSG_CODE_280002", "副本模型不存在",
        "MSG_CODE_280003", "副本达到最大进度",
        "MSG_CODE_280004", "副本挑战达到最大次数",
        "MSG_CODE_280005", "副本重置达到最大次数",
        "MSG_CODE_280006", "副本不能直达关底",
        
        "MSG_CODE_310001", "门派不存在",
        "MSG_CODE_310002", "门派中该成员不存在",
        "MSG_CODE_310003", "该用户已在门派中",
        "MSG_CODE_310004", "当前用户没有权限",
        "MSG_CODE_310005", "该用户不在申请列表",
        "MSG_CODE_310006", "门派成员已达到最大数量",
        "MSG_CODE_310007", "不能选择自己",
        "MSG_CODE_310008", "该用户不能退出门派",
        "MSG_CODE_310009", "本门派中还有其他用户",
        "MSG_CODE_310010", "门派任命使者时间未到",
        "MSG_CODE_310011", "门派捐赠模型不存在",
        "MSG_CODE_310012", "门派捐赠次数达到最大值",
        "MSG_CODE_310013", "门派科技功能不存在",
        "MSG_CODE_310014", "门派科技功能模型不存在",
        "MSG_CODE_310015", "门派科技功能升级条件不满足",
        "MSG_CODE_310016", "门派科技功能等级达到最大值",
        "MSG_CODE_310017", "该用户已是使者",
        "MSG_CODE_310018", "门派更新时间还没到",
        "MSG_CODE_310019", "门派周贡献模型不存在",
        "MSG_CODE_310020", "门派天破阵次数达到最大值",
        "MSG_CODE_310021", "门派破阵模型不存在",
        "MSG_CODE_310022", "门派龙穴模型不存在",
        "MSG_CODE_310023", "门派龙穴不存在",
        "MSG_CODE_310024", "龙穴已经组队",
        "MSG_CODE_310025", "龙穴队员组队CD未结束",
        "MSG_CODE_310026", "龙穴队员组队次数已满",
        "MSG_CODE_310027", "龙穴组队超过上限",
        "MSG_CODE_310028", "门派龙穴副本模型不存在",
        "MSG_CODE_310029", "龙穴没有组队",
        "MSG_CODE_310030", "龙穴不能调整座位",
        "MSG_CODE_310031", "龙穴队员不能相同",
        "MSG_CODE_310032", "龙穴不能探宝",
        "MSG_CODE_310033", "成功挑战龙穴",
        "MSG_CODE_310034", "挑战龙穴失败",
        "MSG_CODE_310035", "龙穴事件模型不存在",
        "MSG_CODE_310036", "龙穴战斗怪物不存在",
        "MSG_CODE_310037", "龙穴不能战斗",
        "MSG_CODE_310038", "集市模型不存在",
        "MSG_CODE_310039", "门派成员模型不存在",
        "MSG_CODE_310040", "门派集市槽位不存在",
        "MSG_CODE_310041", "门派集市兑换模型不存在",
        "MSG_CODE_310042", "门派用户积分不足",
        "MSG_CODE_310043", "门派集市模型不存在",
        "MSG_CODE_310044", "门派集市兑换条件不满足",
        "MSG_CODE_310045", "门派排行战不存在",
        "MSG_CODE_310046", "门派排行战报名时间过期",
        "MSG_CODE_310047", "门派排行战已报名",
        "MSG_CODE_310048", "门派排行战抽奖模型不存在",
        "MSG_CODE_310049", "门派排行战用户未报名",
        "MSG_CODE_310050", "门派排行战抽卡次数达到最大值",
        "MSG_CODE_310051", "门派排行战卡片不存在",
        "MSG_CODE_310052", "门派排行战领导力不足",
        "MSG_CODE_310053", "门派排行战未进行",
        "MSG_CODE_310054", "门派排行战用户不存在",
        "MSG_CODE_310055", "门派排行战战斗CD未结束",
        "MSG_CODE_310056", "门派排行战敌人不存在",
        "MSG_CODE_310057", "已经挑战过该敌人",
        "MSG_CODE_310058", "门派排行战门派不存在",
        "MSG_CODE_310059", "门派福缘阁不存在",
        "MSG_CODE_310060", "门派福缘阁模型不存在",
        "MSG_CODE_310061", "门派聚宝盆模型不存在",
        "MSG_CODE_310062", "门派聚宝盆已抽奖",
        "MSG_CODE_310063", "门派聚宝盆抽奖时间过期",
        "MSG_CODE_310064", "门派排行战卡数量未满足",
        "MSG_CODE_310065", "排行战进行阶段不允许该操作",
        "MSG_CODE_310066", "门派功能开启表模型不存在",
        "MSG_CODE_310067", "门派功能开启条件不满足",
        "MSG_CODE_310068", "门派排行战不能刷新对手",
        "MSG_CODE_310069", "门派用户加入门派的CD未到",
        "MSG_CODE_310070", "门派等级未满足要求",
        "MSG_CODE_310071", "其他龙穴还未挑战",
        
        
        "MSG_CODE_310041", "公会集市兑换模型不存在",
        "MSG_CODE_310042", "公会用户积分不够",
        "MSG_CODE_310043", "公会集市模型不存在",
        "MSG_CODE_310044", "公会集市兑换条件不满足",
        "MSG_CODE_310045", "公会排行战不存在",
        "MSG_CODE_310046", "公会排行战报名时间过期",
        "MSG_CODE_310047", "公会排行战已报名",
        "MSG_CODE_310048", "公会排行战抽奖模型不存在",
        "MSG_CODE_310049", "公会排行战用户没报名",
        "MSG_CODE_310050", "公会排行战用户抽卡次数达到最大值",
        "MSG_CODE_310051", "公会排行战卡片不存在",
        "MSG_CODE_310052", "公会排行战领导力不够",
        "MSG_CODE_310053", "公会排行战不在进行中",
        "MSG_CODE_310054", "公会排行战用户不存在",
        "MSG_CODE_310055", "公会排行战战斗CD未结束",
        "MSG_CODE_310056", "公会排行战敌人不存在",
        "MSG_CODE_310057", "公会排行战敌人已经挑战过",
        "MSG_CODE_310058", "公会排行战公会不存在",
        "MSG_CODE_310059", "公会福缘阁不存在",
        "MSG_CODE_310060", "公会福缘阁模型不存在",
        "MSG_CODE_310061", "公会聚宝盆模型不存在",
        "MSG_CODE_310062", "公会聚宝盆已经抽奖",
        "MSG_CODE_310063", "公会聚宝盆抽奖时间过期",
        "MSG_CODE_310064", "公会排行战卡数量不对",
        "MSG_CODE_310065", "公会排行站进行阶段该操作不允许",
        "MSG_CODE_310066", "公会功能开启表模型不存在",
        "MSG_CODE_310067", "公会功能开启条件不满足",
        "MSG_CODE_310068", "公会排行站不能刷新对手",
        "MSG_CODE_310069", "公会用户加入公会的CD未到",
        "MSG_CODE_310070", "公会门派等级太低",
        "MSG_CODE_310071", "公会龙穴其他龙穴还没有挑战完",
        
    };

    
    if (initialized == false)
    {
        int length = sizeof(languageData) / sizeof(char*);
        for(int i=0;i<length/2;i++)
        {
            m_Datas.setObject(HString::create(languageData[2*i+1]), languageData[2*i]);
            //CCLOG("%s",languageData[2*i]);
        }
    }
    return;
}

const char *HLanguage::getError(int errorcode, const char *defaultvalue, bool usedefault)
{
    if (usedefault)
        return defaultvalue;
    
    char buff[100];
    sprintf(buff, "MSG_CODE_%d", errorcode);
    HString* str = (HString*) (HLanguage::getInstance()->m_Datas.objectForKey(buff));
    if (str == NULL) {        
        return ccLocalizedString("HSYS_UNKNOWN_ERROR");        
    }
    return str->getCString();
}
